# Generated by Django 5.2.3 on 2025-06-18 09:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True, verbose_name='Назва категорії')),
                ('slug', models.SlugField(max_length=200, unique=True, verbose_name='URL')),
                ('description', models.TextField(blank=True, verbose_name='Опис')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активна')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата створення')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата оновлення')),
                ('sort_order', models.PositiveIntegerField(default=0, verbose_name='Порядок сортування')),
            ],
            options={
                'verbose_name': 'категорія',
                'verbose_name_plural': 'категорії',
                'ordering': ['sort_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Назва товару')),
                ('slug', models.SlugField(max_length=255, unique=True, verbose_name='URL')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Ціна')),
                ('old_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Стара ціна')),
                ('description', models.TextField(blank=True, verbose_name='Опис')),
                ('features', models.TextField(blank=True, verbose_name='Характеристики')),
                ('status', models.CharField(choices=[('in_stock', 'В наявності'), ('out_of_stock', 'Немає в наявності'), ('on_order', 'Під замовлення')], default='in_stock', max_length=20, verbose_name='Статус')),
                ('warranty', models.PositiveSmallIntegerField(choices=[(6, '6 місяців'), (12, '1 рік'), (24, '2 роки'), (36, '3 роки')], default=12, verbose_name='Гарантія (місяців)')),
                ('quantity', models.PositiveIntegerField(default=1, verbose_name='Кількість')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата створення')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата оновлення')),
                ('is_featured', models.BooleanField(default=False, verbose_name='Рекомендований')),
                ('is_new', models.BooleanField(default=False, verbose_name='Новинка')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='catalog.category', verbose_name='Категорія')),
            ],
            options={
                'verbose_name': 'товар',
                'verbose_name_plural': 'товари',
                'ordering': ['-created_at'],
            },
        ),
    ]
